---
- name: Scan VM with complyctl
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Ensure complytime user workspace"
      ansible.builtin.file:
        path: "~/complytime"
        state: directory
        mode: "0700"

    - name: "Copy Assessment Plan"
      ansible.builtin.copy:
        src: "assessment-plan.json"
        dest: "~/complytime/"
        mode: "0640"

    - name: "Execute 'generate' command with customized Assessment Plan"
      ansible.builtin.command:
        cmd: "complyctl generate"
        chdir: "~"
      changed_when: false

    - name: "Execute 'scan' command"
      ansible.builtin.command:
        cmd: "complyctl scan --with-md"
        chdir: "~"
      changed_when: false

    - name: "Check if there is 'No Findings.' string in assessment-results.md"
      ansible.builtin.command:
        cmd: "grep -q 'No Findings.' ~/complytime/assessment-results.md"
      changed_when: false
      failed_when: false
      register: result_grep_findinds

    - name: "Assert: VM is 100% compliant based on complyctl scan"
      ansible.builtin.assert:
        that: result_grep_findinds.rc == 0
        fail_msg: "Provisioned Box is not 100% compliant"
        success_msg: "Good Job!! :)"
...
