---
- name: Playbook to configure the VM
  hosts: all
  become: true
  vars:
    # Variables used for fixing the system
    var_sudo_logfile: "/var/log/sudo.log"
    var_accounts_user_umask: "027"
  tasks:
    - name: "Ensure desired packages are installed"
      ansible.builtin.dnf:
        name:
          - firewalld # Fix package_firewalld_installed
          - openssh-clients
          - openssh-server
          - qemu-guest-agent
          - tree
        state: present

    - name: "Fix sudo_custom_logfile"
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: 'Defaults logfile={{ var_sudo_logfile }}'
        validate: /usr/sbin/visudo -cf %s

    - name: "Fix accounts_umask_etc_login_defs"
      ansible.builtin.replace:
        path: /etc/login.defs
        regexp: ^(\s*)UMASK(\s+).*
        replace: '\g<1>UMASK\g<2>{{ var_accounts_user_umask }}'
...
