name: Vagrant VM Validation (VirtualBox)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache Vagrant boxes
        id: cache-boxes
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-boxes-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-boxes-

      - name: Install System Dependencies (Ansible, VirtualBox)
        run: |
          sudo add-apt-repository universe -y
          sudo apt-get update
          sudo apt-get install -y ansible virtualbox

      - name: Run Ansible Playbook Syntax Check
        run: ansible-playbook vm_hardening.yml validate_vm_complyctl.yml --syntax-check

      # --- Install Vagrant (direct download) ---
      - name: Install Vagrant
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vagrant
          vagrant --version

      - name: Add Vagrant box (if not cached)
        if: steps.cache-boxes.outputs.cache-hit != 'true'
        run: |
          vagrant box add https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-VirtualBox-42-1.1.x86_64.vagrant.virtualbox.box --name f42-cloud-base || true

      - name: Bring up Vagrant VM and Validate
        run: |
          vagrant up --provision --provider=virtualbox

      - name: Clean up Vagrant VM
        if: always()
        run: |
          vagrant destroy -f
